[alist-host]
type = webdav
url = http://gtr-host:5244/dav
vendor = other
user = admin
pass = ZR3t5ZqS2czp5sSVAtqswl9ZzVt0g134IVIePFU

[alist-eth]
type = webdav
url = http://gtr-eth:5244/dav
vendor = other
user = admin
pass = IX4B9CMPUg_wdgoIn4a6exsaCnNI7iM8sHnXtHc

