# numbered_command = false
numbered_command = true

focus_on_create = true
use_trash = false
watch_files = true
xdg_open = false
xdg_open_fork = false
case_insensitive_ext = false

custom_commands = []

[display]
# default, hsplit
mode = "default"

automatically_count_files = true
collapse_preview = true
# ratios for parent view (optional), current view and preview
column_ratio = [1, 3, 5]
scroll_offset = 6
show_borders = true
show_hidden = false
show_icons = true
tilde_in_titlebar = true
# none, absolute, relative
line_number_style = "absolute"

# size, mtime, user, gourp, perm. can be combined with |.
# `none` to disable, `all` to enable all
# all and none can't be combined with other options
linemode = "size"

[display.sort]
# lexical, mtime, natural, size, ext
sort_method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
# max_preview_size = 2097152                           # 2MB
max_preview_size = 2147483648                          # 2GB
preview_script = "~/.config/joshuto/preview_file.sh"

[search]
# insensitive, sensitive, smart
string_case_sensitivity = "insensitive"
# see above
glob_case_sensitivity = "sensitive"
# see above
regex_case_sensitivity = "sensitive"
# see above
fzf_case_sensitivity = "insensitive"

[tab]
# inherit, home, root
home_page = "home"
