[gtr]
  comment = GTR Share
  path = /data
  valid users = gtr
  ## 不共享备份用的文件夹, 增加安全性
  veto files = /*backup/ /PiliPlus/

# [D盘备份]
#   comment = D盘备份（只读）
#   path = /home/gtr/share/Seagate/D盘备份
#   valid users = gtr
#   browsable = yes
#   writeable = yes
# 
# [F盘备份]
#   comment = F盘备份（只读）
#   path = /home/gtr/share/WD_Elements_2621/F盘备份
#   valid users = gtr
#   browsable = yes
#   read only = yes
# 
# [music]
#   comment = music
#   path = /home/gtr/share/Seagate/D盘备份/Data/音乐
#   valid users = gtr
#   browsable = yes
#   writeable = yes
